# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'brookesiapos.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QSizePolicy, QStatusBar,
    QToolBar, QWidget)

class Ui_brookesiapos(object):
    def setupUi(self, brookesiapos):
        if not brookesiapos.objectName():
            brookesiapos.setObjectName(u"brookesiapos")
        brookesiapos.resize(1000, 600)
        brookesiapos.setMinimumSize(QSize(1000, 600))
        brookesiapos.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.action_sales = QAction(brookesiapos)
        self.action_sales.setObjectName(u"action_sales")
        icon = QIcon()
        icon.addFile(u"qrc/icons/shoppingcar.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_sales.setIcon(icon)
        self.action_customers = QAction(brookesiapos)
        self.action_customers.setObjectName(u"action_customers")
        icon1 = QIcon()
        icon1.addFile(u"qrc/icons/client.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_customers.setIcon(icon1)
        self.action_products = QAction(brookesiapos)
        self.action_products.setObjectName(u"action_products")
        icon2 = QIcon()
        icon2.addFile(u"qrc/icons/product.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_products.setIcon(icon2)
        self.action_providers = QAction(brookesiapos)
        self.action_providers.setObjectName(u"action_providers")
        icon3 = QIcon()
        icon3.addFile(u"qrc/icons/provider.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_providers.setIcon(icon3)
        self.action_taxes = QAction(brookesiapos)
        self.action_taxes.setObjectName(u"action_taxes")
        icon4 = QIcon()
        icon4.addFile(u"qrc/icons/tax.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_taxes.setIcon(icon4)
        self.action_settings = QAction(brookesiapos)
        self.action_settings.setObjectName(u"action_settings")
        icon5 = QIcon()
        icon5.addFile(u"qrc/icons/settings.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_settings.setIcon(icon5)
        self.action_about = QAction(brookesiapos)
        self.action_about.setObjectName(u"action_about")
        icon6 = QIcon()
        icon6.addFile(u"qrc/icons/about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_about.setIcon(icon6)
        self.action_minimize = QAction(brookesiapos)
        self.action_minimize.setObjectName(u"action_minimize")
        icon7 = QIcon()
        icon7.addFile(u"qrc/icons/minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_minimize.setIcon(icon7)
        self.action_exit = QAction(brookesiapos)
        self.action_exit.setObjectName(u"action_exit")
        icon8 = QIcon()
        icon8.addFile(u"qrc/icons/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_exit.setIcon(icon8)
        self.centralwidget = QWidget(brookesiapos)
        self.centralwidget.setObjectName(u"centralwidget")
        brookesiapos.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(brookesiapos)
        self.statusbar.setObjectName(u"statusbar")
        brookesiapos.setStatusBar(self.statusbar)
        self.toolbar = QToolBar(brookesiapos)
        self.toolbar.setObjectName(u"toolbar")
        self.toolbar.setMovable(False)
        self.toolbar.setFloatable(False)
        brookesiapos.addToolBar(Qt.TopToolBarArea, self.toolbar)

        self.toolbar.addAction(self.action_sales)
        self.toolbar.addAction(self.action_customers)
        self.toolbar.addAction(self.action_products)
        self.toolbar.addAction(self.action_providers)
        self.toolbar.addAction(self.action_taxes)
        self.toolbar.addAction(self.action_settings)
        self.toolbar.addAction(self.action_about)
        self.toolbar.addAction(self.action_minimize)
        self.toolbar.addAction(self.action_exit)

        self.retranslateUi(brookesiapos)

        QMetaObject.connectSlotsByName(brookesiapos)
    # setupUi

    def retranslateUi(self, brookesiapos):
        brookesiapos.setWindowTitle("")
        self.action_sales.setText(QCoreApplication.translate("brookesiapos", u"Sales. F1", None))
#if QT_CONFIG(tooltip)
        self.action_sales.setToolTip(QCoreApplication.translate("brookesiapos", u"Sales. F1", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_sales.setShortcut(QCoreApplication.translate("brookesiapos", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.action_customers.setText(QCoreApplication.translate("brookesiapos", u"Customers. F2", None))
#if QT_CONFIG(tooltip)
        self.action_customers.setToolTip(QCoreApplication.translate("brookesiapos", u"Customers. F2", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_customers.setShortcut(QCoreApplication.translate("brookesiapos", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.action_products.setText(QCoreApplication.translate("brookesiapos", u"Products. F3", None))
#if QT_CONFIG(tooltip)
        self.action_products.setToolTip(QCoreApplication.translate("brookesiapos", u"Products. F3", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_products.setShortcut(QCoreApplication.translate("brookesiapos", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.action_providers.setText(QCoreApplication.translate("brookesiapos", u"Providers. F4", None))
#if QT_CONFIG(tooltip)
        self.action_providers.setToolTip(QCoreApplication.translate("brookesiapos", u"Providers. F4", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_providers.setShortcut(QCoreApplication.translate("brookesiapos", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.action_taxes.setText(QCoreApplication.translate("brookesiapos", u"Taxes and measures. F5", None))
#if QT_CONFIG(tooltip)
        self.action_taxes.setToolTip(QCoreApplication.translate("brookesiapos", u"Taxes and mesaures. F5", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_taxes.setShortcut(QCoreApplication.translate("brookesiapos", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.action_settings.setText(QCoreApplication.translate("brookesiapos", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.action_settings.setToolTip(QCoreApplication.translate("brookesiapos", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.action_about.setText(QCoreApplication.translate("brookesiapos", u"About", None))
#if QT_CONFIG(tooltip)
        self.action_about.setToolTip(QCoreApplication.translate("brookesiapos", u"About", None))
#endif // QT_CONFIG(tooltip)
        self.action_minimize.setText(QCoreApplication.translate("brookesiapos", u"Minimize", None))
#if QT_CONFIG(tooltip)
        self.action_minimize.setToolTip(QCoreApplication.translate("brookesiapos", u"Minimize", None))
#endif // QT_CONFIG(tooltip)
        self.action_exit.setText(QCoreApplication.translate("brookesiapos", u"Exit", None))
#if QT_CONFIG(tooltip)
        self.action_exit.setToolTip(QCoreApplication.translate("brookesiapos", u"Exit", None))
#endif // QT_CONFIG(tooltip)
        self.toolbar.setWindowTitle("")
    # retranslateUi

